# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - streamlitnlptopic

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://streamlitnlp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_06e2b526332b4255a3c6e9cc3c0b3db4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_aba1bf1e801242f08b7d6fe3122b6ced }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: streamlitnlp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_06e2b526332b4255a3c6e9cc3c0b3db4 }}/streamlitapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'streamlitnlptopic'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9ed9b05759f64b14a18663db7dd44b9e }}
        images: 'streamlitnlp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_06e2b526332b4255a3c6e9cc3c0b3db4 }}/streamlitapp:${{ github.sha }}'